name: PR Checks

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  checks:
    uses: defi-wonderland/aztec-ci-actions/.github/workflows/run-tests.yml@v0
    with:
      run-js-tests: false
      run-noir-tests: true
      runner: ubuntu-latest
    secrets: inherit
